language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
    - cd app/
    - "pip install -r ../requirements-dev.txt"
    - "pip install coveralls"
before_script: 
    - mysql -e 'create database citoengine;'
    - python manage.py syncdb --noinput
    - python manage.py migrate
# command to run tests
script: 
    - coverage run --source='.' --omit=tests*,fabfile*,*admin*,*urls*,*manage*,*/settings/*,*wsgi*,*/migrations/*  manage.py test
after_success:
    - coveralls
notifications:
  email:
    - sysadmin@citoengine.org
