language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=settings.dev
# following is workaround to travis build system bug. See https://github.com/travis-ci/travis-ci/issues/7940
  - BOTO_CONFIG=/dev/null
install: 
    - cd app/
    - "cp settings/citoengine.conf-dev settings/citoengine.conf"
    - "pip install -r ../requirements-dev.txt"
    - "pip install coveralls"
before_script: 
    - mysql -e 'create database citoengine;'
    - python manage.py migrate
# command to run tests
script: 
    - coverage run --source='.' --omit=tests*,fabfile*,*admin*,*urls*,*manage*,*/settings/*,*wsgi*,*/migrations/*  manage.py test
after_success:
    - coveralls
notifications:
  email:
    - sysadmin@citoengine.org

sudo: false