language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
    - "pip install -r requirements.txt"
    - "pip install coveralls"
before_script: 
    - mysql -e 'create database cito;'
    - python manage.py syncdb --noinput
# command to run tests
script: 
    - coverage run --source='.' --omit=tests*,fabfile*,*admin*,*urls*,*manage*,*/settings/*,*wsgi*  manage.py test
after_success:
    - coveralls
notifications:
  email:
    - sysadmin@citoengine.org
